// GENERATED by lens/scripts/export-pricing.mts - do not edit by hand.
//
// Plan facts live in the Lens entitlement catalog, which is checked against
// the gate itself. Editing this file by hand would let the pricing page
// advertise something the product denies. Re-run the export instead.

export interface Plan {
  id: string;
  name: string;
  blurb: string;
  /** `null` on Free - there is nothing to charge. */
  monthly: string | null;
  annualMonthly: string | null;
  annualTotal: string | null;
  perSeat: boolean;
  workspaces: string;
  capabilities: string[];
}

/** Discount applied to annual billing. Copy says "Save 10%" - NOT
 *  "2 months free", which would overstate it. */
export const ANNUAL_DISCOUNT_PERCENT = 10;

/** The free trial every paid plan starts with. It is configured on the Paddle
 *  prices; this is what the page may SAY about it. */
export const TRIAL_DAYS = 30;

/** Shown beside the prices: which buyers are billed in another currency, and
 *  where tax appears. Every price in PLANS is USD. */
export const PRICE_CURRENCY_NOTE = "Prices are in US dollars. Customers in the UK, Ireland and Australia are billed in GBP, EUR and AUD respectively. Tax is calculated for your location and shown at checkout, before you pay.";

export const PLANS: Plan[] = [
  {
    "id": "free",
    "name": "Free",
    "blurb": "The full API workspace, no account needed.",
    "monthly": null,
    "annualMonthly": null,
    "annualTotal": null,
    "perSeat": false,
    "workspaces": "1",
    "capabilities": [
      "1 workspace",
      "Request editor, environments and run history",
      "Local mock servers",
      "Execution plans — author and run them in the app",
      "OpenAPI and collection import, GitHub-backed sync"
    ]
  },
  {
    "id": "basic",
    "name": "Basic",
    "blurb": "Catch PR Review drift with your Code graph and Spec.",
    "monthly": "$18.99",
    "annualMonthly": "$17.09",
    "annualTotal": "$205.09",
    "perSeat": false,
    "workspaces": "3",
    "capabilities": [
      "3 workspaces",
      "Everything in Free",
      "Code graph — every endpoint, mapped to its code",
      "PR Review — drift in every pull request, against your Code graph and Spec",
      "Drift-infill scaffolding"
    ]
  },
  {
    "id": "pro",
    "name": "Pro",
    "blurb": "Put your AI tools on the same Code graph you work from.",
    "monthly": "$27.99",
    "annualMonthly": "$25.19",
    "annualTotal": "$302.29",
    "perSeat": false,
    "workspaces": "10",
    "capabilities": [
      "10 workspaces",
      "Everything in Basic",
      "AI Assistant — bring your own key",
      "MCP server for Claude, Cursor, Copilot and more",
      "Endpoint context graph — contracts, mocks, callers and tests per endpoint",
      "GitLab, Bitbucket and Azure DevOps"
    ]
  },
  {
    "id": "team",
    "name": "Team",
    "blurb": "Make PR Review drift a build failure, for the whole team.",
    "monthly": "$36.99",
    "annualMonthly": "$33.29",
    "annualTotal": "$399.49",
    "perSeat": true,
    "workspaces": "Unlimited",
    "capabilities": [
      "Unlimited workspaces",
      "Everything in Pro",
      "Command-line interface for CI pipelines",
      "Seats and per-device activation",
      "Single sign-on (OIDC)"
    ]
  }
];
